### ISSUE TITLE
Doubt about the activities

### ISSUE THREAD

**Issue by Gianlu94** [nishantrai18/homage#2]
Hi,

I have downloaded the dataset and I am currently looking at **train_list.csv**. I noticed that you have:

- fold_clothes and folding_clothes
- iron_clothes and ironing_clothes
- listen_to_music and listening_to_music
- pack_suitcase and packing_suitcase
- unpack_from_a_suitcase and unpacking_suitcase

Are these ones referring to the same activity (so, is there an error in the annotation?). If not, what is the difference?

**Comment by nishantrai18** [comment]
Indeed, that seems to be an issue on the labeling end. They should semantically refer to the same activity.
