### ISSUE TITLE
Missing first-person views in the validation set (and other issues)

### ISSUE THREAD

**Issue by alceballosa** [nishantrai18/homage#4]
Hi!

I downloaded the dataset last year. However, while exploring the data I found that some videos (all of the videos by participant p0001) in the validation partition do not have the first-person view (v000). Is it possible to somehow obtain such videos?

Additionally, I noticed that the same video_id appears twice in the train_list.csv file:

p0030_r001_a000,go_to_sleep 
p0030_r001_a000,work_at_table

Upon inspecting the annotation files, it seems that the videos for that entry are of a go_to_sleep instance but the labels are for a work_at_table scene.

There is a similar situation for p0028_r004_a000 and p0028_r004_a001, albeit the first-person video and one of the third-person videos do match with the annotation.

Also, I've found 45 videos for which the annotations file is empty. I can provide a list if required but I'm not sure if that is intended.

Thank you in advance for your time.

**Comment by qiaomu-miao** [comment]
Hello, do you know what is the meaning of each word in the filename I think p means person, what does 'r001' and 'a000' mean? Is there any detailed documentation explaining the data?

**Comment by nishantrai18** [comment]
Thanks for the questions and apologies for the late reply, both {kozuka.kazuki, ishizaka.shun} AT jp.panasonic.com will be able to help with these detailed queries :)

**Comment by nishantrai18** [comment]
Hello @qiaomu-miao , additional details regarding your questions have been provided here - https://github.com/nishantrai18/homage/issues/5#issuecomment-1273979055

In short, r001 refers to the room (it's an internal field you do not need to be bothered by), while a000 refers to the action id, similarly p and v refer to person and view. More details are provided in the other answer i linked.
