### ISSUE TITLE
How can I associate the json files with mkv files?

### ISSUE THREAD

**Issue by qwangku** [nishantrai18/homage#5]
Thanks for sharing this great resource.  Do you have an existing DataLoader for atomic-action recognition for HOMAGE?
I didn't find one so I decided to create it myself.  My first step is to generate a dictionary structure like this following the same method in write_csv.py:

```
{ 'p0033_r004_a000' :
[[91, 150, 'hold notebook', 2], [121, 150, 'close notebook', 1], [151, 180, 'take sth from table', 1], [151, 180, 'put paper swh', 1], [151, 180, 'take paper from swh', 1], [151, 180, 'put sth on table', 1], [211, 240, 'put paper swh', 1], [271, 300, 'put paper swh', 1], [271, 300, 'put sth on table', 1], [211, 330, 'take paper from swh', 4], [211, 330, 'take sth from table', 4], [361, 450, 'put paper swh', 3], [121, 480, 'hold paper', 12], [481, 510, 'take sth from table', 1], [481, 510, 'take notebook from swh', 1], [481, 540, 'put notebook swh', 2], [481, 570, 'hold notebook', 3], [541, 570, 'take book from swh', 1], [541, 570, 'put book swh', 1], [541, 570, 'put sth on table', 1], [571, 600, 'take pen from swh', 1], [541, 630, 'take sth from table', 3], [601, 630, 'take book from swh', 1], [601, 630, 'put book swh', 1], [511, 660, 'hold book', 5], [691, 720, 'put sth on table', 1], [691, 720, 'take book from swh', 1], [691, 720, 'put book swh', 1], [691, 720, 'take paper from swh', 1], [691, 720, 'put paper swh', 1], [691, 720, 'take notebook from swh', 1], [691, 720, 'put notebook swh', 1], [541, 750, 'hold pen', 7], [691, 750, 'hold book', 2], [691, 750, 'hold paper', 2], [691, 750, 'hold notebook', 2], [691, 810, 'take sth from table', 4], [781, 810, 'take book from swh', 1], [781, 810, 'take notebook from swh', 1], [781, 810, 'take paper from swh', 1], [781, 840, 'put sth on table', 2], [781, 840, 'hold book', 2], [781, 840, 'hold notebook', 2], [781, 840, 'hold pen', 2], [781, 840, 'hold paper', 2], [811, 840, 'put book swh', 1], [811, 840, 'put notebook swh', 1], [811, 840, 'put paper swh', 1], [841, 900, 'put pen swh', 2]]}
```
However, I noticed there exist multiple video datafile that correspond to this "p0033_r004_a000". 
./train_data/action_split_data/V1.0/p0033/p0033_r004_v001_a000.mkv
./train_data/action_split_data/V1.0/p0033/p0033_r004_v003_a000.mkv
./train_data/action_split_data/V1.0/p0033/p0033_r004_v000_a000.mkv
./train_data/action_split_data/V1.0/p0033/p0033_r004_v002_a000.mkv

I am not sure what "v00X" means here, but how can I find the correct MKV files based on this "p0033_r004_a000", which was generated from the json files in annotation_files/atomic_actions/ folder?

**Comment by nishantrai18** [comment]
Hello @qwangku , there are multiple videos for the specific person, room and action because we supply videos from various views. v000 to the ego-centric, while the rest are other third person views.

The exact naming for each video is p[person_id]_r[room_id]_v[view_id]_a[action_id]. Hope this clarifies some of your questions :)

**Comment by qwangku** [comment]
@nishantrai18  Thanks for the information.  I have two follow-up questions:
(1) Can you point me to some atomic-action recognition scripts or results for HOMAGE dataset?  I can find the training split from annotation_files/atomic_actions/,  but I didn't find val/eval split for atomic-actions.
(2) It seems for a specific capture, the lengths of ego-centric video and the 3rd person video are not the same. For example,  p0003_r002_v001_a013.mkv is obviously longer than p0003_r002_v000_a013.mkv.  So some frames in {'label': 'hold utensil', 'start': 1171, 'end': 1260} does not exist in the shorter video. Is this expected and how did you handle this in the DataLoader?
